# Generated by Django 4.2.18 on 2025-02-03 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="musician_pics/"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True)),
                (
                    "bands",
                    models.ManyToManyField(
                        blank=True, related_name="members", to="app.band"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("year", models.PositiveIntegerField()),
                ("album", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="song_images/"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "musician",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.musician"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamingLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("spotify", "Spotify"),
                            ("apple_music", "Apple Music"),
                            ("bandcamp", "Bandcamp"),
                            ("youtube", "YouTube"),
                            ("amazon_music", "Amazon Music"),
                            ("soundcloud", "SoundCloud"),
                            ("tidal", "Tidal"),
                            ("extra1", "Extra1"),
                            ("extra2", "Extra2"),
                            ("extra3", "Extra3"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaming_links",
                        to="app.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_title", models.CharField(max_length=255)),
                ("song_artist", models.CharField(max_length=255)),
                ("reasoning", models.TextField()),
                (
                    "unique_url",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "musician",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.musician"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("spotify", "Spotify"),
                            ("bluesky", "Bluesky"),
                            ("extra1", "Extra1"),
                            ("extra2", "Extra2"),
                            ("extra3", "Extra3"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="app.musician",
                    ),
                ),
            ],
        ),
    ]
