# Generated by Django 4.2.18 on 2025-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="picture_credit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
