# Generated by Django 4.2.18 on 2025-02-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_musician_picture_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
