# Generated by Django 4.2.18 on 2025-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_song_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("twitter", "Twitter"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("youtube", "YouTube"),
                    ("spotify", "Spotify"),
                    ("bluesky", "Bluesky"),
                    ("bandcamp", "Bandcamp"),
                    ("extra2", "Extra2"),
                    ("extra3", "Extra3"),
                ],
                max_length=50,
            ),
        ),
    ]
