# Generated by Django 4.2.18 on 2025-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_sociallink_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songsubmission",
            name="reasoning",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="songsubmission",
            name="song_artist",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="songsubmission",
            name="song_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
