# Generated by Django 4.2.18 on 2025-02-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_songsubmission_reasoning_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="platform",
        ),
        migrations.AddField(
            model_name="sociallink",
            name="description",
            field=models.CharField(default="lame", max_length=200),
            preserve_default=False,
        ),
    ]
