# Generated by Django 4.2.18 on 2025-02-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_sociallink_platform_sociallink_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musician",
            name="website",
        ),
    ]
