# Generated by Django 4.2.18 on 2025-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_musician_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="streaminglink",
            name="platform",
        ),
        migrations.AddField(
            model_name="streaminglink",
            name="name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
