# Generated by Django 4.2.18 on 2025-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_streaminglink_platform_streaminglink_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="hashtag",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
