# Generated by Django 4.2.18 on 2025-02-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_sitelinks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteLinks",
            new_name="SiteLink",
        ),
    ]
